# Generated by Django 4.2.11 on 2024-06-27 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0002_like_user_email_user_fen"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="password",
            field=models.CharField(default=123, max_length=150),
            preserve_default=False,
        ),
    ]
