# Generated by Django 4.2.11 on 2024-06-27 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0004_remove_user_email_alter_user_face_img_path"),
    ]

    operations = [
        migrations.AddField(
            model_name="commodity",
            name="introduce",
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="commodity",
            name="img",
            field=models.ImageField(null=True, upload_to="images/commodity"),
        ),
    ]
