# Generated by Django 4.2.11 on 2024-06-27 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0005_commodity_introduce_alter_commodity_img"),
    ]

    operations = [
        migrations.CreateModel(
            name="jf_Commodity",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("introduce", models.CharField(max_length=255)),
                ("number", models.IntegerField()),
                ("price", models.FloatField()),
                ("img", models.ImageField(null=True, upload_to="images/commodity")),
            ],
        ),
        migrations.AlterField(
            model_name="user",
            name="face_img_path",
            field=models.ImageField(blank=True, null=True, upload_to="images/user/"),
        ),
    ]
