# Generated by Django 4.2.11 on 2024-07-09 11:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0006_jf_commodity_alter_user_face_img_path"),
    ]

    operations = [
        migrations.AddField(
            model_name="like",
            name="good",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="myapp.commodity",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="like",
            name="number",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="like",
            name="user",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="myapp.user",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="like",
            name="id",
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
