# Generated by Django 4.2.11 on 2024-07-16 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0011_cart_quantity"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cart",
            name="quantity",
            field=models.IntegerField(default=1),
        ),
    ]
